default:
  image: nixpkgs/cachix-flakes
  before_script:
    - git config --global user.email ""
    - git config --global user.name "Gitlab CI"
    - git config --global push.followTags true
    - git checkout $CI_COMMIT_REF_NAME
    - git remote set-url origin "https://gitlab-ci:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git pull origin $CI_COMMIT_REF_NAME
    - cachix use "$CACHIX_CACHE_NAME"

variables:
  NIX_PATH: nixpkgs=channel:nixos-unstable
  FLAKEREF: $CI_PROJECT_DIR
  CACHIX_CACHE_NAME: simonoscr
  NIX_BUILD_FLAGS: "--no-update-lock-file --print-build-logs --show-trace"

stages:
  - check
  - build
  - release

check:
  stage: check
  script:
    - nix flake show --all-systems
    - nix flake check $NIX_BUILD_FLAGS
    - |
      if ! git diff --quiet --exit-code; then
        git add -A;
        git commit -m "style: alejandra, deadnix, statix, shellcheck, ...";
        git push -o ci.skip origin "$CI_COMMIT_REF_NAME"
      fi

build:
  stage: build
  script:
    - nix-shell -p jq --run "nix flake archive --json | jq -r '.path,(.inputs|to_entries[].value.path)' | cachix push $CACHIX_CACHE_NAME"
  only:
    - main

release:
  image: node:slim
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - git config --global user.email ""
    - git config --global user.name "Gitlab CI"
    - git config --global push.followTags true
    - git checkout $CI_COMMIT_REF_NAME
    - git remote set-url origin "https://gitlab-ci:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git pull origin $CI_COMMIT_REF_NAME
    - npm install --location=global semantic-release @semantic-release/gitlab @semantic-release/changelog conventional-changelog-conventionalcommits@7.0.2 @semantic-release/commit-analyzer @semantic-release/git
  script:
    - semantic-release
  only:
    - main
