keys:
  - &user_simon_age age14mjnxlu4c7fdppuev0y5263f8y2yv0d80480czltqxz3ev8encgqcjc9gk
  - &server_oscar_age age1wq5z9whagwqm5vyt0jqgw5syk5txaw0mj0hekxxpdakysqk8qg2spds49q
  - &user_work_age
creation_rules:
  - path_regex: home/simon/secrets/[^/]+\.yaml$
  #- path_regex: ~/nixsecrets/secrets/simon/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *user_simon_age
  - path_regex: home/oscar/secrets/[^/]+\.yaml$
  #- path_regex: ~/nixsecrets/secrets/oscar/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *server_oscar_age
        - *user_simon_age
  - path_regex: home/work/secrets/[^/]+\.yaml$
  #- path_regex: ~/nixsecrets/secrets/work/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *user_work_age
        - *user_simon_age
