keys:
  - &user_simon_age age14mjnxlu4c7fdppuev0y5263f8y2yv0d80480czltqxz3ev8encgqcjc9gk
  - &server_host_age age12e956d0p6n8nagqrkje0fflgqxrf085zg4k79d2xk0d5422ns52q3yhve0
creation_rules:
  - path_regex: home/simon/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *user_simon_age
  - path_regex: home/nixos/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *server_host_age
        - *user_simon_age
