#!/bin/sh

# Install Starship
if ! command -v starship >/dev/null 2>&1; then
    echo "Installing Starship"
    curl -sS https://starship.rs/install.sh | sh -s -- -y
fi

# Create directory for zsh plugins
mkdir -p ~/.zsh/plugins/

# Install subdomules
yadm submodule update --init --recursive
