name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [merged]
  workflow_dispatch:

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - run: nix flake check

  release:
    needs: checks
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""          
          minor_pattern: "feat:"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          bump_each_commit: true
          bump_each_commit_patch_pattern: "fix:"
          search_commit_body: false
          user_format_type: "json"
          enable_prerelease_mode: false
          debug: false
          version_from_branch: false

