name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [merged]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          minorList: feat, feature
          patchList: fix, bugfix, perf, refactor, ref, test, ci
          patchAll: false
          skipInvalidTags: false
          noVersionBumpBehavior: "warn"

      - name: Determine Tags
        id: tags
        run: |
          echo "fromTag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
          echo "toTag=$(git describe --tags `git rev-list --tags --max-count=1 --skip=1`)" >> $GITHUB_ENV


      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          fromTag: ${{ env.fromTag }}
          toTag: ${{ env.toTag }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
