name: SemVersioning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  semver:
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "false"
          git-message: "chore: {version}"
          tag-prefix: ""
          release-count: "10"
          output-file: "CHANGELOG.md"
          create-summary: "true"
          version-file: ""
          skip-version-file: "true"
