name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [merged]
  workflow_dispatch:

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - run: nix flake check

  release:
    needs: checks
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
