name: check nix flake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install nix flake
        uses: cachix/install-nix-action@v22
        with:
          install_url: https://nixos.org/nix/install
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check
