name: update-flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          nix-options: --debug --log-format raw
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated

      - name: Print PR number
        run: echo Pull request number is ${{ steps.update.outputs.pull-request-number }}.
