name: update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install nix flake
        uses: DeterminateSystems/nix-installer-action@main

      - name: update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          nix-options: --debug --log-format raw
          pr-assignees: simonoscr
          pr-title: "update flake.lock"
          pr-labels: |
            dependencies
            automated
          pr-body: |
            flake.lock successfully updated:

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          commit-msg: "chore: flake.lock Update"

      - name: print pr number
        run: echo Pull request number is ${{ steps.update.outputs.pull-request-number }}.
